ALTER TABLE users
  ADD COLUMN seller_type VARCHAR(12) NOT NULL DEFAULT 'private' AFTER role,
  ADD COLUMN org_name VARCHAR(150) NULL DEFAULT NULL AFTER seller_type,
  ADD COLUMN org_inn VARCHAR(20) NULL DEFAULT NULL AFTER org_name;
